---
abstract: 'A naive custom RIPv2 daemon'
author:
  - 'Heikki Hannikainen, OH7LZB <hessu@hes.iki.fi>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112621'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AMPR-Rip44
no_index:
  directory:
    - t
    - inc
requires:
  IO::Socket::Multicast: 0
  Test::More: 0
version: 0.03
